### ISSUE TITLE
Iteration count for password based encryption should be at least 1000

### ISSUE THREAD

**Issue by naskovai** [zhuqianqian/Passbook#10]
As part of some research about the [common crypto mistakes that developers make](https://littlemaninmyhead.wordpress.com/2017/04/22/top-10-developer-crypto-mistakes/), I noticed that your application has one of them.

In [com.z299studio.pb.Crypto](https://github.com/zhuqianqian/Passbook/blob/d9620e07c505e9c2165921dc1189c9d1c7591b48/app/src/main/java/com/z299studio/pb/Crypto.java#L48) you're initializing a PBEKeySpec instance with an iteration count of 800.  However, [The recommended iteration count in the RFC published in September 2000 was 1000.](https://cryptosense.com/blog/parameter-choice-for-pbkdf2/)

**Comment by zhuqianqian** [comment]
Fixed, new default iteration count is 1600.
