### ISSUE TITLE
Import from Google Drive

### ISSUE THREAD

**Issue by Julline** [zhuqianqian/Passbook#4]
Hi. The app is very cool. But, when data sync completed, the changes appear only after restarting the program. There are ways to fix this?

**Comment by zhuqianqian** [comment]
Hello Julline, this is an issue, and I am planing to fix it next update. Thank you.

**Comment by zhuqianqian** [comment]
Issue fixed with 2.5.1 release, cheers!
Thank you @Julline for reporting this error.
